git: warn about shallow/partial clones
Previously, you would get a panic like this, as in https://github.com/martinvonz/jj/issues/2022:

```sh
$ jj init --git-repo=.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ObjectNotFound { object_type: "commit", hash: "a430c04e28fbc783f99abbc701aaef35dd103803", source: Error { code: -3, klass: 9, message: "object not found - no match for id (a430c04e28fbc783f99abbc701aaef35dd103803)" } }', lib/src/git.rs:199:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This commit handles the panic and adds a hint. It now looks like this:

```sh
$ cargo run -- init ../jj-shallow --git-repo ../jj-shallow
Error: Failed to import refs from underlying Git repo: Missing commit: 0a349dcbfb7e20a21eeb9cc65c9878b0d9b19a0c
Hint: Is this Git repository a shallow or partial clone (cloned with the --depth or --filter argument)? jj currently does not support shallow/partial clones. To use jj with this repository, try unshallowing the repository (https://stackoverflow.com/q/6802145) or re-cloning with the full repository contents.
$ cargo run -- -R ../jj-shallow st
Error: Failed to import refs from underlying Git repo: Missing commit: 0a349dcbfb7e20a21eeb9cc65c9878b0d9b19a0c
Hint: Is this Git repository a shallow or partial clone (cloned with the --depth or --filter argument)? jj currently does not support shallow/partial clones. To use jj with this repository, try unshallowing the repository (https://stackoverflow.com/q/6802145) or re-cloning with the full repository contents.
```

Notes:

- `jj init` succeeds even though importing Git refs fails, which is not at all obvious from the error message.
- I was unable to add a test for this because there's no way to create a shallow/partial clone using `git2`. It seems that libgit2 released shallow clone in v1.7.0 (2023-07-17, 3 weeks ago at the time of this writing), but the Rust `git2` bindings have not been updated. It also doesn't seem like we shell out to `git` in any of our tests, so I don't want to add a new runtime test dependency on `git`.