cli: add `jj config unset`
Allow unsetting config values similar to `git config unset`.

```bash
$ jj config set --user some-key some-val
$ jj config get some-key
some-val
$ jj config unset --user some-key
$ jj config get some-key
Config error: configuration property "some-key" not found
For help, see https://martinvonz.github.io/jj/latest/config/.
```

Unsetting nonexistent keys will result in an error:
```bash
$ jj config unset --user nonexistent
Error: configuration property "nonexistent" not found
For help, see https://martinvonz.github.io/jj/latest/config/.
```

If unsetting a key leaves the hosting table empty, the table is removed
as well.

Given the following config:
```toml
[table]
key = "value"

[another-table]
key = "value"
```

Running `jj config unset --user table.key` will leave us with:
```toml
[another-table]
key = "value"
```